language: php
php:
  - '7.2.1'
node_js:
  - '10.15.1'

branches:
  only:
    - develop

sudo: true

services: postgresql

before_install:
- sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_10.15.1 | sudo -E bash -
- sudo apt-get install -y nodejs
- composer self-update

install:
- composer install
- cp .env.dist .env
- php bin/console doctrine:database:create
- php bin/console doctrine:schema:create

script:
  - php bin/phpunit