language: php
php:
- '7.2.1'

env:
  - NODE_VERSION="10.15.1"

branches:
  only:
    - develop

sudo: true

services: postgresql

before_install:
- nvm install $NODE_VERSION
- composer self-update

install:
- composer install
- cp .env.dist .env
- php bin/console doctrine:database:create
- php bin/console doctrine:schema:create

script:
  - php bin/phpunit