version: '2'
services:
    web:
        container_name: symfony_web
        build: ./docker/php
        links:
            - dbserver
        volumes:
            - /var/www:/var/www/app
        ports:
            - 8000:80
            
    dbserver:
        container_name: symfony_db
        image: postgres:9
        restart: always
        volumes:
            - /var/www/portfolio/var/db:/var/lib/postgresql 
        ports:
            - 5432:5432       
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    pgadmin:
        container_name: symfony_pgadmin
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        links:
            - dbserver
