version: '2'
services:
    web:
        container_name: symfony-web
        build: ./docker/php
        links:
            - dbserver
        volumes:
            - /var/www:/var/www/app
        ports:
            - "8000:80"
            
    dbserver:
        container_name: symfony_db
        image: postgres:9
        restart: always
        volumes:
            - /var/www/portfolio/var/db:/var/lib/postgresql 
        ports:
            - 5432:5432       
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mydb

    pgadmin:
        container_name: symfony_pgadmin
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: d.delima@outlook.fr
            PGADMIN_DEFAULT_PASSWORD: root
        links:
            - dbserver

