index:
    path: /
    controller: App\Controller\IndexController::index

show_list:
    path: /posts
    controller: App\Controller\PostController::showAll

show_details:
    path: /post/{slug}
    controller: App\Controller\PostController::showDetails

admin:
    path: /admin
    controller: App\Controller\AdminController::index

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

api_login_check:
    path: /api/login_check
