index:
    path: /
    controller: App\Controller\DefaultController::index

posts:
    path: /posts
    controller: App\Controller\DefaultController::posts

admin:
    path: /admin
    controller: App\Controller\AdminController::index

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

api_login_check:
    path: /api/login_check
